# Pull Request Template

pull_request_title: >
  # Briefly describe the changes in your pull request.

related_issues: >
  # Link to the relevant issues, e.g., `Fixes #123` or `Closes #456`.

description_of_changes: >
  # Provide a detailed description of the changes made in this pull request. Explain why the changes are necessary and any important context.

type_of_change:
  - [ ] Bug fix
  - [ ] New feature
  - [ ] Breaking change
  - [ ] Refactoring
  - [ ] Documentation update
  - [ ] Other (please specify): ___________________

how_to_test: >
  # Describe the steps required to test the changes. This could include:
  # - Cloning the branch
  # - Running tests
  # - Manually verifying changes
  # - Any specific instructions related to testing

screenshots_if_applicable: >
  # If your PR includes UI changes, add screenshots to demonstrate how it looks before and after the changes.

checklist:
  - [ ] I have followed the [contribution guidelines](CONTRIBUTING.md) (if applicable).
  - [ ] I have tested the changes locally.
  - [ ] I have written appropriate tests for the changes.
  - [ ] I have updated the documentation (if applicable).
  - [ ] The code is properly formatted (e.g., following linters or style guides).
  - [ ] All existing tests pass (run `npm te
