ThisBuild / scalaVersion     := "3.8.4"
ThisBuild / version          := "0.0.0.snapshot"
ThisBuild / organization     := "org.finos.cdm"
ThisBuild / organizationName := "cdm-scala"

// Configure resolver to use Google Artifact Registry mirror
ThisBuild / resolvers := Seq(
  "Artifact Registry Mirror" at "https://europe-west1-maven.pkg.dev/production-208613/maven-central/"
)

// Credentials for Artifact Registry, loaded from a real credentials file generated by the
// CI pipeline's setup-sbt-credentials.sh
ThisBuild / credentials += Credentials(Path.userHome / ".sbt" / ".credentials")

// Tell Coursier to use our configured resolvers
ThisBuild / externalResolvers := resolvers.value

// Jackson version, aligned with the main pom.xml's <jackson.version>
val jacksonVersion = "2.17.1"

// ScalaTest version, cross-published for Scala 3
val scalaTestVersion = "3.2.19"

lazy val root = (project in file("."))
  .settings(
    name := "cdm-scala",
    libraryDependencies ++= Seq(
      "org.scalatest" %% "scalatest" % scalaTestVersion % Test,
      "com.fasterxml.jackson.module" %% "jackson-module-scala" % jacksonVersion,
      "com.fasterxml.jackson.datatype" % "jackson-datatype-jsr310" % jacksonVersion
    )
  )