import Dependencies._

ThisBuild / scalaVersion     := "3.8.4"
ThisBuild / version          := "0.0.0.snapshot"
ThisBuild / organization     := "org.finos.cdm"
ThisBuild / organizationName := "cdm-scala"

// Configure resolver to use Google Artifact Registry mirror
ThisBuild / resolvers := Seq(
  "Artifact Registry Mirror" at "https://europe-west1-maven.pkg.dev/production-208613/maven-central/"
)

// Credentials for Artifact Registry (loaded from a real credentials file so that both
// the main build and the project/ meta-build resolve consistently - see global
// ~/.sbt/1.0/plugins/credentials.sbt generated by the CI pipeline)
ThisBuild / credentials += Credentials(Path.userHome / ".sbt" / ".credentials")

// Tell Coursier to use our configured resolvers
ThisBuild / externalResolvers := resolvers.value

val versions = new {
  // jackson-module-scala only gained Scala 3 support starting with Jackson 2.13.0 (experimental)
  // and full support in later releases. 2.10.0 predates Scala 3 support entirely, which is why
  // "jackson-module-scala_3:2.10.0" could not be found on the proxy. Aligned with the main
  // pom.xml's <jackson.version> (2.17.1), which is Scala 3 compatible.
  val jackson = "2.17.1"
}

lazy val root = (project in file("."))
  .settings(
    name := "cdm-scala",
    libraryDependencies ++= Seq(
      scalaTest % Test,
      "com.fasterxml.jackson.module" %% "jackson-module-scala" % versions.jackson,
      "com.fasterxml.jackson.datatype" % "jackson-datatype-jsr310" % versions.jackson
    )
  )