import Dependencies._

ThisBuild / scalaVersion     := "2.12.8"
ThisBuild / version          := "0.0.0.snapshot"
ThisBuild / organization     := "org.finos.cdm"
ThisBuild / organizationName := "cdm-scala"

// Configure resolver to use Google Artifact Registry mirror
ThisBuild / resolvers := Seq(
  "Artifact Registry Mirror" at "https://europe-west1-maven.pkg.dev/production-208613/maven-central/"
)

// Credentials for Artifact Registry (loaded from a real credentials file so that both
// the main build and the project/ meta-build resolve consistently - see global
// ~/.sbt/1.0/plugins/credentials.sbt generated by the CI pipeline)
ThisBuild / credentials += Credentials(Path.userHome / ".sbt" / ".credentials")

// Tell Coursier to use our configured resolvers
ThisBuild / externalResolvers := resolvers.value

val versions = new {
  val jackson = "2.10.0"
}

lazy val root = (project in file("."))
  .settings(
    name := "cdm-scala",
    libraryDependencies ++= Seq(
      scalaTest % Test,
      "com.fasterxml.jackson.module" %% "jackson-module-scala" % versions.jackson,
      "com.fasterxml.jackson.datatype" % "jackson-datatype-jsr310" % versions.jackson
    )
  )