version: '1.0'
stages:
  - setup
  - build
  - distribute
  - finalise
steps:

  main_clone:
    title: Cloning main repository...
    stage: 'setup'
    type: git-clone
    git: github
    repo: "${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}"
    revision: "${{CF_REVISION}}"

  SetProperties:
    stage: 'setup'
    title: Setup build
    image: alpine/git
    commands:
      - cf_export REPO_PATH=${{CF_VOLUME_PATH}}/${{CF_REPO_NAME}}
      - cf_export MVN_DEPLOY_FLAGS="-s ${{CF_VOLUME_PATH}}/${{CF_REPO_NAME}}/settings.xml -Denv.CI_DEPLOY_PASSWORD=${{CI_DEPLOY_PASSWORD}} -Denv.CI_DEPLOY_USERNAME=${{CI_DEPLOY_USERNAME}}"

  ReleaseProperties:
    stage: 'setup'
    title: Setup release build
    image: alpine/git
    when:
      condition:
        all:
          releaseNameNotDefined: "${{TAG_REPO}} == true"
    commands:
      - cf_export RELEASE_NAME=${{TAG_NAME}}
      - cf_export MAVEN_BUILD_PROFILES="daml,scala,typescript,golang,csharp8,csharp9,kotlin,full"
      - cf_export MVN_DEPLOY_FILE_FLAGS="${{MVN_DEPLOY_FLAGS}} -Durl=https://oss.sonatype.org/service/local/staging/deploy/maven2 -DrepositoryId=ossrh-distro"

  SnapshotProperties:
    stage: 'setup'
    title: Setup snapshot build
    image: alpine/git
    when:
      condition:
        all:
          releaseNameNotDefined: "${{TAG_REPO}} == false"
    commands:
      - cf_export RELEASE_NAME=${{GLOBAL_RELEASE_VERSION}}.${{CF_BRANCH_TAG_NORMALIZED}}-SNAPSHOT
      - cf_export MAVEN_BUILD_PROFILES="daml,scala,typescript,golang,csharp8,csharp9,kotlin"
      - cf_export MVN_DEPLOY_FILE_FLAGS="${{MVN_DEPLOY_FLAGS}} -Durl=https://oss.sonatype.org/content/repositories/snapshots -DrepositoryId=ossrh"

  Build:
    stage: 'build'
    title: Maven build
    fail_fast: false
    image: maven:3.8.2-jdk-11-slim
    working_directory: ./
    when:
      condition:
        all:
          isNotRelease: "${{TAG_REPO}} == false"
    commands:
      - mvn versions:set -DnewVersion=${{RELEASE_NAME}} versions:update-child-modules
      - mvn ${MVN_DEPLOY_FLAGS} clean deploy -P "${{MAVEN_BUILD_PROFILES}}"

  BuildParallelTasks:
    stage: 'build'
    type: parallel
    steps:
      BuildDaml:
        stage: 'build'
        title: DAML build
        fail_fast: false
        image: digitalasset/daml-sdk:1.3.0
        working_directory: ./rosetta-source/
        shell: bash
        commands:
          - daml build -o target/cdm-daml-${{RELEASE_NAME}}.dar
      BuildScala:
        stage: 'build'
        title: Scala build
        fail_fast: false
        image: mozilla/sbt:8u292_1.5.7
        working_directory: ./rosetta-source/target/classes/cdm/scala
        shell: bash
        commands:
          - sbt compile
          - sbt package
      BuildCSharp8:
        stage: 'build'
        title: CSharp8 build
        fail_fast: false
        image: mcr.microsoft.com/dotnet/core/sdk:3.1
        working_directory: ./rosetta-source/target/classes/cdm/csharp8/NetStandard.2.1
        shell: bash
        commands:
          - dotnet build Cdm/Cdm.csproj
          - dotnet test Test/Test.csproj
          - dotnet publish Cdm/Cdm.csproj -c release -o ./app
      BuildCSharp9:
        stage: 'build'
        title: CSharp9 build
        fail_fast: false
        image: mcr.microsoft.com/dotnet/sdk:5.0
        working_directory: ./rosetta-source/target/classes/cdm/csharp9/Net.5.0
        shell: bash
        commands:
          - dotnet build Cdm/Cdm.csproj
          - dotnet test Test/Test.csproj
          - dotnet publish Cdm/Cdm.csproj -c release -o ./app

  DeployParallelTasks:
    stage: 'build'
    type: parallel
    steps:
      DeployDaml:
        stage: 'build'
        title: DAML deploy
        fail_fast: false
        image: maven:3.8.2-jdk-11-slim
        working_directory: ./rosetta-source/
        shell: bash
        commands:
          - cd ${{REPO_PATH}}/rosetta-source/target
          - tar -cvzf cdm-daml-${{RELEASE_NAME}}.tar.gz cdm-daml-${{RELEASE_NAME}}.dar
          - mvn deploy:deploy-file ${{MVN_DEPLOY_FILE_FLAGS}} -Dfile=cdm-daml-${{RELEASE_NAME}}.tar.gz -DgroupId=org.finos.cdm -DartifactId=cdm-daml -Dversion=${{RELEASE_NAME}} -Dpackaging=tar.gz -DgeneratePom=true
      DeployScala:
        stage: 'build'
        title: Scala deploy
        fail_fast: false
        image: maven:3.8.2-jdk-11-slim
        working_directory: ./rosetta-source/target/classes/cdm/scala
        shell: bash
        commands:
          - cd ${{REPO_PATH}}/rosetta-source/target/classes/cdm/scala/target/scala-2.12
          - mv cdm-scala_2.12-0.0.0.snapshot.jar cdm-scala-${{RELEASE_NAME}}.jar
          - mvn deploy:deploy-file ${{MVN_DEPLOY_FILE_FLAGS}} -Dfile=cdm-scala-${{RELEASE_NAME}}.jar -DgroupId=org.finos.cdm -DartifactId=cdm-scala -Dversion=${{RELEASE_NAME}} -DgeneratePom=true
      DeployCSharp8:
        stage: 'build'
        title: CSharp8 deploy
        fail_fast: false
        image: maven:3.8.2-jdk-11-slim
        working_directory: ./rosetta-source/target/classes/cdm/csharp8/NetStandard.2.1
        shell: bash
        commands:
          - tar -cvzf cdm-csharp8-${{RELEASE_NAME}}.tar.gz app
          - mvn deploy:deploy-file ${{MVN_DEPLOY_FILE_FLAGS}} -Dfile=cdm-csharp8-${{RELEASE_NAME}}.tar.gz -DgroupId=org.finos.cdm -DartifactId=cdm-csharp8 -Dversion=${{RELEASE_NAME}} -Dpackaging=tar.gz -DgeneratePom=true
      DeployCSharp9:
        stage: 'build'
        title: CSharp9 deploy
        fail_fast: false
        image: maven:3.8.2-jdk-11-slim
        working_directory: ./rosetta-source/target/classes/cdm/csharp9/Net.5.0
        shell: bash
        commands:
          - tar -cvzf cdm-csharp9-${{RELEASE_NAME}}.tar.gz app
          - mvn deploy:deploy-file ${{MVN_DEPLOY_FILE_FLAGS}} -Dfile=cdm-csharp9-${{RELEASE_NAME}}.tar.gz -DgroupId=org.finos.cdm -DartifactId=cdm-csharp9 -Dversion=${{RELEASE_NAME}} -Dpackaging=tar.gz -DgeneratePom=true
      DeployTypeScript:
        stage: 'build'
        title: TypeScript deploy
        fail_fast: false
        image: maven:3.8.2-jdk-11-slim
        working_directory: ./rosetta-source/target/classes/cdm
        shell: bash
        commands:
          - tar -cvzf cdm-typescript-${{RELEASE_NAME}}.zip typescript
          - mvn deploy:deploy-file ${{MVN_DEPLOY_FILE_FLAGS}} -Dfile=cdm-typescript-${{RELEASE_NAME}}.zip -DgroupId=org.finos.cdm -DartifactId=cdm-typescript -Dversion=${{RELEASE_NAME}} -DgeneratePom=true
      DeployGo:
        stage: 'build'
        title: Go deploy
        fail_fast: false
        image: maven:3.8.2-jdk-11-slim
        working_directory: ./rosetta-source/target/classes/cdm
        shell: bash
        commands:
          - tar -cvzf cdm-golang-${{RELEASE_NAME}}.tar.gz golang
          - mvn deploy:deploy-file ${{MVN_DEPLOY_FILE_FLAGS}} -Dfile=cdm-golang-${{RELEASE_NAME}}.tar.gz -DgroupId=org.finos.cdm -DartifactId=cdm-golang -Dversion=${{RELEASE_NAME}} -Dpackaging=tar.gz -DgeneratePom=true
      DeployKotlin:
        stage: 'build'
        title: Kotlin deploy
        fail_fast: false
        image: maven:3.8.2-jdk-11-slim
        working_directory: ./rosetta-source/
        shell: bash
        commands:
          - cd ${{REPO_PATH}}/rosetta-source/target/classes/cdm/kotlin
          - mvn -f kotlin-build-pom.xml versions:set -DnewVersion=${{RELEASE_NAME}}
          - mvn -f kotlin-build-pom.xml ${MVN_DEPLOY_FLAGS} clean deploy

  DistributeDaml:
    stage: 'distribute'
    title: Maven DAML distribution
    fail_fast: false
    image: maven:3.8.2-jdk-11-slim
    working_directory: ./distribution
    commands:
      - mvn -f daml-pom.xml versions:set -DnewVersion=${{RELEASE_NAME}}
      - mvn -f daml-pom.xml ${MVN_DEPLOY_FLAGS} clean deploy

  DistributeScala:
    stage: 'distribute'
    title: Maven Scala distribution
    fail_fast: false
    image: maven:3.8.2-jdk-11-slim
    working_directory: ./distribution
    commands:
      - mvn -f scala-pom.xml versions:set -DnewVersion=${{RELEASE_NAME}}
      - mvn -f scala-pom.xml ${MVN_DEPLOY_FLAGS} clean deploy

  DistributeCSharp8:
    stage: 'distribute'
    title: Maven CSharp8 distribution
    fail_fast: false
    image: maven:3.8.2-jdk-11-slim
    working_directory: ./distribution
    commands:
      - mvn -f csharp8-pom.xml versions:set -DnewVersion=${{RELEASE_NAME}}
      - mvn -f csharp8-pom.xml ${MVN_DEPLOY_FLAGS} clean deploy

  DistributeCSharp9:
    stage: 'distribute'
    title: Maven CSharp9 distribution
    fail_fast: false
    image: maven:3.8.2-jdk-11-slim
    working_directory: ./distribution
    commands:
      - mvn -f csharp9-pom.xml versions:set -DnewVersion=${{RELEASE_NAME}}
      - mvn -f csharp9-pom.xml ${MVN_DEPLOY_FLAGS} clean deploy

  DistributeTypeScript:
    stage: 'distribute'
    title: Maven TypeScript distribution
    fail_fast: false
    image: maven:3.8.2-jdk-11-slim
    working_directory: ./distribution
    commands:
      - mvn -f typescript-pom.xml versions:set -DnewVersion=${{RELEASE_NAME}}
      - mvn -f typescript-pom.xml ${MVN_DEPLOY_FLAGS} clean deploy

  DistributeGo:
    stage: 'distribute'
    title: Maven Golang distribution
    fail_fast: false
    image: maven:3.8.2-jdk-11-slim
    working_directory: ./distribution
    commands:
      - mvn -f golang-pom.xml versions:set -DnewVersion=${{RELEASE_NAME}}
      - mvn -f golang-pom.xml ${MVN_DEPLOY_FLAGS} clean deploy

  DistributeKotlin:
    stage: 'distribute'
    title: Maven Kotlin distribution
    fail_fast: false
    image: maven:3.8.2-jdk-11-slim
    working_directory: ./distribution
    commands:
      - mvn -f kotlin-pom.xml versions:set -DnewVersion=${{RELEASE_NAME}}
      - mvn -f kotlin-pom.xml ${MVN_DEPLOY_FLAGS} clean deploy

  NotifySlackOnFail:
    stage: 'finalise'
    title: Trigger Slack dev channel notification if master build failed
    image: codefresh/cli
    when:
      branch:
        only:
          - master
      condition:
        any:
          BuildSnapshotFailed: steps.BuildSnapshot.result == 'error'
          buildReleaseFailed: steps.BuildRelease.result == 'error'
          buildDamlFailed: steps.BuildDaml.result == 'error'
          buildScalaFailed: steps.BuildScala.result == 'error'
          buildCSharp8Failed: steps.BuildCSharp8.result == 'error'
          buildCSharp9Failed: steps.BuildCSharp9.result == 'error'
          deployDamlFailed: steps.DeployDaml.result == 'error'
          deployScalaFailed: steps.DeployScala.result == 'error'
          deployTypeScriptFailed: steps.DeployTypeScript.result == 'error'
          deployCSharp8Failed: steps.DeployCSharp8.result == 'error'
          deployCSharp9Failed: steps.DeployCSharp9.result == 'error'
          deployGoFailed: steps.DeployGo.result == 'error'
          deployKotlinFailed: steps.DeployKotlin.result == 'error'
          buildJavaDocsFailed: steps.BuildJavaDocs.result == 'error'
          distributeNormalFailed: steps.BuildDistributionNormal.result == 'error'
          distributeReleaseFailed: steps.BuildDistributionRelease.result == 'error'
          distributeDamlFailed: steps.DistributeDaml.result == 'error'
          distributeScalaFailed: steps.DistributeScala.result == 'error'
          distributeTypeScriptFailed: steps.DistributeTypeScript.result == 'error'
          distributeCSharp8Failed: steps.DistributeCSharp8.result == 'error'
          distributeCSharp9Failed: steps.DistributeCSharp9.result == 'error'
          distributeGoFailed: steps.DistributeGo.result == 'error'
          distributeKotlinFailed: steps.DistributeKotlin.result == 'error'
          distributeJavaDocsFailed: steps.DistributeJavaDocs.result == 'error'
    commands:
      - export SAFE_COMMIT_AUTHOR='${{CF_COMMIT_AUTHOR}}'
      - export COMMIT_AUTHOR=${SAFE_COMMIT_AUTHOR:-MissingAuthor}
      - export SAFE_REPO_NAME='${{CF_REPO_NAME}}'
      - export REPO_NAME=${SAFE_REPO_NAME:-NoRepo}
      - export SAFE_COMMIT_MESSAGE='${{CF_COMMIT_MESSAGE}}'
      - export COMMIT_MESSAGE=${SAFE_COMMIT_MESSAGE:-NoCommitMsg}
      - echo Author is $SAFE_COMMIT_AUTHOR and commit msg is $SAFE_COMMIT_MESSAGE and repo is $SAFE_REPO_NAME
      - echo After substitution author is $COMMIT_AUTHOR and commit msg is $COMMIT_MESSAGE and repo is $REPO_NAME
      - codefresh run slack-notifier -v REPO_NAME="${REPO_NAME}" -v COMMIT_AUTHOR="${COMMIT_AUTHOR}" -v COMMIT_MESSAGE="${COMMIT_MESSAGE}"  --detach

  FailPipeline:
    stage: 'finalise'
    title: Fail pipeline if the Maven build failed
    image: codefresh/cli
    when:
      condition:
        any:
          normalBuildFailure: steps.BuildSnapshot.result == 'failure'
          releaseBuildFailure: steps.BuildRelease.result == 'failure'
          damlBuildFailure: steps.BuildDaml.result == 'failure'
          scalaBuildFailure: steps.BuildScala.result == 'failure'
          cSharp8BuildFailure: steps.BuildCSharp8.result == 'failure'
          cSharp9BuildFailure: steps.BuildCSharp9.result == 'failure'
          damlDeployFailure: steps.DeployDaml.result == 'failure'
          scalaDeployFailure: steps.DeployScala.result == 'failure'
          typeScriptDeployFailure: steps.DeployTypeScript.result == 'failure'
          cSharp8DeployFailure: steps.DeployCSharp8.result == 'failure'
          cSharp9DeployFailure: steps.DeployCSharp9.result == 'failure'
          goDeployFailure: steps.DeployGo.result == 'failure'
          kotlinDeployFailure: steps.DeployKotlin.result == 'failure'
          javaDocsBuildFailure: steps.BuildJavaDocs.result == 'failure'
          distributeNormalFailure: steps.BuildDistributionNormal.result == 'failure'
          distributeReleaseFailure: steps.BuildDistributionRelease.result == 'failure'
          distributeDamlFailure: steps.DistributeDaml.result == 'failure'
          distributeScalaFailure: steps.DistributeScala.result == 'failure'
          distributeTypeScriptFailure: steps.DistributeTypeScript.result == 'failure'
          distributeCSharp8Failure: steps.DistributeCSharp8.result == 'failure'
          distributeCSharp9Failure: steps.DistributeCSharp9.result == 'failure'
          distributeGoFailure: steps.DistributeGo.result == 'failure'
          distributeKotlinFailure: steps.DistributeKotlin.result == 'failure'
          distributeJavaDocsFailure: steps.DistributeJavaDocs.result == 'failure'
    commands:
      - exit 1

  TagRepo:
    stage: 'finalise'
    title: Tag git repo with release name
    image: alpine/git
    when:
      condition:
        all:
          buildPassed: steps.BuildRelease.result == 'success'
          isRelease: "${{TAG_REPO}}"
    commands:
      - echo This is a release build, tag repos with release name [${{RELEASE_NAME}}]
      - git fetch --prune https://${{REGNOSYS_OPS}}:${{REGNOSYS_OPS_TOKEN}}@github.com/${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}.git "+refs/tags/*:refs/tags/*"
      - git tag ${{RELEASE_NAME}}
      - git push https://${{REGNOSYS_OPS}}:${{REGNOSYS_OPS_TOKEN}}@github.com/${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}.git ${{RELEASE_NAME}}

  StartNextBuild:
    stage: 'finalise'
    title: Build rosetta-navigation if on master
    image: codefresh/cli
    when:
      branch:
        only:
          - master
      condition:
        all:
          buildPassed: steps.BuildSnapshot.result == 'success'
          variableDefined: "${{TAG_REPO}} == false"
          skipNextBuild: "${{SKIP_NEXT_BUILD}} == false"
    commands:
      - codefresh run REGnosys/rosetta-navigation/rosetta-navigation --branch master --detach
