[build]
  base = "website"
  command = "npm run build"
  publish = "build"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . ../{src,website}/"

# Serve JSON schema files for browser display
[[headers]]
  for = "/schemas/*/*.json"
  [headers.values]
    Content-Type = "application/json; charset=utf-8"
    Access-Control-Allow-Origin = "*"
    X-Content-Type-Options = "nosniff"
