name: Feature
description: Use this template to suggest feature enhancements for the CDM.
type: "Feature"
labels: "Awaiting Triage"
body:
  - type: textarea
    attributes:
      label: Background
      description: Provide the business context for the proposed feature, including the problem it aims to solve and the reason why it is needed.
      placeholder: |
        Use plain language, avoiding niche business or technical terminology
        
        Explain the benefit to the model and/or community
        
        Provide details of existing or proposed solutions
    validations:
      required: true

  - type: textarea
    attributes:
      label: Proposal
      description: Detail the proposed changes clearly, breaking them into sections where appropriate to improve comprehension. Where possible, include visual aids such as before/after images to illustrate model enhancements.
      placeholder: |
        Describe the scope of the change, work item, or deliverable
    validations:
      required: true

  - type: textarea
    attributes:
      label: Compatibility
      description: If applicable, describe any potential compatibility issues this change may introduce with existing versions. Please review the list of backwardly incompatible changes and design principles for further guidance.
      placeholder: |
        Is this feature backward compatible?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Context
      description: Provide any additional context or relevant information that may assist in understanding the proposal, such as related issues or dependencies.
      placeholder: |
        Provide details of existing or proposed solutions
        
        Identify the relevant Working Group for community contributions (if applicable)

        Specify the version of the CDM the issue relates to
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        > [!TIP]
        > Providing evidence of prior approval for the proposed change from a relevant CDM Working Group will significantly help the review process. 
        > This additional context will assist CDM maintainers and participants in evaluating the proposal effectively.
