name: Feature
description: Use this template to suggest feature enhancements for the CDM.
type: "Feature"
body:
  - type: textarea
    attributes:
      label: Background
      description: Provide the business context for the proposed feature, including the problem it aims to solve and the reason why it is needed.
      placeholder: > - include the source of the Issue i.e. is it from the Roadmap, from a Working Group recommendation, github discussions etc
> - describe the scope of the change, work item or deliverable
> - be written in “plain English” i.e. try not to use niche business or technical terminology
> - describe the benefit to the model and/or the community
> - identify the Working Group where community members can contribute to the change, if applicable
> - include details of existing or proposed solutions in respect of this issue
> - the version of the CDM that the Issue relates to
    validations:
      required: true

  - type: textarea
    attributes:
      label: Proposal
      description: Detail the proposed changes clearly, breaking them into sections where appropriate to improve comprehension. Where possible, include visual aids such as before/after images to illustrate model enhancements.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Compatibility
      description: If applicable, describe any potential compatibility issues this change may introduce with existing versions. Please review the list of backwardly incompatible changes and design principles for further guidance.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Context
      description: Provide any additional context or relevant information that may assist in understanding the proposal, such as related issues or dependencies.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |

        > [!NOTE]
        > When submitting a feature request, please ensure that it:
        > - **Important!** Please ensure that your issue has an appropriate label before submitting.
        > - **Labels**: Apply a relevant label (e.g., `bug`, `enhancement`, etc.) to help us categorize and prioritize this issue.
        > - Identifies the source of the issue (e.g., Roadmap, Working Group recommendation, GitHub discussions, etc.).
        > - Clearly defines the scope of the change, work item, or deliverable.
        > - Uses simple, clear language, avoid niche business or technical jargon where possible.
        > - Explains the benefit of the change to the model and/or the community.
        > - Specifies the relevant Working Group where community members can contribute, if applicable.
        > - Includes existing or proposed solutions related to the issue.
        > - Mentions the version of the CDM the issue pertains to.
        > - Is manageable—larger proposals should be broken down into smaller, more digestible issues.
        > 
        > This template includes sections to help you provide the right level of detail for your feature request.
        >
        > Once you're satisfied with your submission, you may delete any tips, notes, or alerts from the page.

        > [!TIP]
        > Providing evidence of prior approval for the proposed change from a relevant CDM Working Group will significantly help the review process. 
        > This additional context will assist CDM maintainers and participants in evaluating the proposal effectively.
