name: Task
description: Used to break down larger features into implementable units of work
type: "Task"
body:
  - type: input
    attributes:
      label: Related Feature
      description: Please provide the name or link to an existing feature this task is related to (e.g., #feature-name or #issue-number).
      placeholder: "e.g., #123, 'Feature X'"
    validations:
      required: false
  - type: textarea
    attributes:
      label: Background
      description: Please provide the business context of the Issue i.e. what is required and why.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        > [!NOTE]
        > Any Issue must:
        > - include the source of the Issue i.e. is it from the Roadmap, from a Working Group recommendation, github discussions etc
        > - describe the scope of the change, work item or deliverable
        > - be written in “plain English” i.e. try not to use niche business or technical terminology
        > - describe the benefit to the model and/or the community
        > - identify the Working Group where community members can contribute to the change, if applicable
        > - include details of existing or proposed solutions in respect of this issue
        > - the version of the CDM that the Issue relates to
        > - be manageable i.e. larger proposals should be broken down into multiple smaller Issues to make them easier to digest
        > 
        > Sections are provided in this template to help create the Issue with the correct level of detail.
        >
        > All _Tips_, _Notes_ and other alerts can be deleted from the page when you are happy with the 
        > content.


        > [!TIP]
        > The more evidence that you can provide of prior approval for the proposed change from a 
        > CDM Working Group the better. This will assist the CDM maintainers and participants
        > when reviewing the proposa
