name: Task
description: Used to break down larger features into actionable units of work.
type: "Task"
body:
  - type: textarea
    attributes:
      label: Background
      description: Provide the business context for this task, including what is required and why.
    validations:
      required: true
      
- type: input
    attributes:
      label: Parent Feature
      description: If this task is linked to an existing feature, please provide the feature name or reference.
      placeholder: "e.g., #123"
    validations:
      required: false

  - type: textarea
    attributes:
      label: Task Details
      description: Provide a detailed description of the task, including its objectives, deliverables, and expected outcomes.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Context
      description: Add any relevant information that may assist in understanding or completing the task (e.g., related issues, dependencies, or constraints).
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        > [!NOTE]
        > - **Important!** Please ensure that your issue has an appropriate label before submitting.
        > - **Labels**: Apply a relevant label (e.g., `bug`, `enhancement`, etc.) to help us categorize and prioritize this issue.

        > [!TIP]
        > The more detailed and clear the task description, the easier it will be for contributors
        > to understand the requirements and scope. If this task is part of a larger initiative, 
        > providing context can help with alignment across teams.
