name: Other Issue
description: I have an issue not covered by FR,BUG or TASK
body:
  - type: textarea
    attributes:
      label: Background
      description: Please provide the business context of the Issue i.e. what is required and why.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
    validations:
      required: true
