name: Bug Report
description: Use this template to report a bug or unexpected behavior in the system.
type: "Bug"
body:
  - type: textarea
    attributes:
      label: Issue Summary
      description: Briefly describe the issue, including any error messages, unexpected behavior, or system malfunctions.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Provide a detailed step-by-step process to reproduce the issue. Include any relevant inputs, configurations, or conditions.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen when performing the action or process.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Actual Behavior
      description: Describe the actual behavior or outcome that occurred, including any discrepancies from the expected behavior.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Context
      description: Provide any additional information, such as logs, screenshots, or related issues that may assist in troubleshooting.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |

        > [!TIP]
        > Providing clear evidence of bug and steps to reproduce helps maintainers and participants in reviewing and prioritizing the bug.

