name: Other Issue
type: "Other"
description: Use this template to report an issue that doesn't fall under Feature Request, Task, or Bug categories.
body:
  - type: textarea
    attributes:
      label: Background
      description: Provide the business context of the issue, including what is required, why it's necessary, and any relevant details that will help clarify the situation.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Context
      description: Provide any additional context, related information, or details that may assist in understanding the issue, such as dependencies, potential impact, or external factors.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |

        > [!NOTE]
        > Please ensure that the issue is described clearly and includes all necessary details for an effective resolution. 
        > If possible, reference any related discussions or documentation that could help clarify the issue.
        > - **Important!** Please ensure that your issue has an appropriate label before submitting.
        > - **Labels**: Apply a relevant label (e.g., `bug`, `enhancement`, etc.) to help us categorize and prioritize this issue.

        > [!TIP]
        > The more context and specific information you can provide, the easier it will be for maintainers to understand and resolve the issue quickly.
