model:
  name: Common Domain Model
dependencies:
generators:
  namespaces:
  - cdm.*
  - com.rosetta.model
  tabulators:
    types:
      - cdm.event.workflow.WorkflowStep
      - cdm.event.common.TradeState
