model:
  name: Common Domain Model
generators:
  namespaces:
    - cdm.*
    - com.rosetta.model
namespaceConfig:
  - id: cdmFixml
    namespace: cdm.fixml.*
    readOnly: true
    schemaConfig:
      schema: cdmFixml
      configPath: xml-config/cdm.fixml-xml-config.json
