// Configure resolver to use Google Artifact Registry mirror for plugins
resolvers := Seq(
  "Artifact Registry Mirror" at "https://europe-west1-maven.pkg.dev/production-208613/maven-central/"
)

// Credentials for Artifact Registry (loaded from a real credentials file so that both
// the main build and the project/ meta-build resolve consistently - see global
// ~/.sbt/1.0/plugins/credentials.sbt generated by the CI pipeline)
credentials += Credentials(Path.userHome / ".sbt" / ".credentials")

// Tell Coursier to use our configured resolvers
externalResolvers := resolvers.value

addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.3.0")
