name: Close Issues Marked as Abandoned (Projects v2)

run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: workflow_dispatch
jobs:
  TEST-RUN:
    runs-on: ubuntu-latest
        steps:
      - name: Close Abandoned Issues in Projects v2
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_TOKEN }}
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."


