name: Close Issues Marked as Abandoned (Projects v2)

on:
  workflow_dispatch:  # Allows manual triggering from the GitHub UI
  issues:
    types:
      - opened
jobs:
  titlePrefixCheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          # script: |
          #   const projectId = "PVT_kwDOC-y4YM4Ayrox"; // <-- Replace this with your Project V2 Node ID
          #   const statusFieldId = PVTSSF_lADOC-y4YM4AyroxzgomHbc"; // <-- Replace with ID of 'Status' field
          #   const abandonedOptionId = "a3ed8e08"; // <-- Replace with ID for 'Abandoned' option

      - name: Set repo
        run: gh repo set-default user/private-repo

      - name: Close Issue
        run: gh issue close --comment "Auto-closing issue" "1"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
