name: PDM Code Scan

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read
  actions: read
  security-events: write

jobs:
  pdm-code-scan:
    name: Run PDM Code Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build (compile only)
        run: mvn -B -V -DskipTests install -q

      - name: Run PDM on modules
        run: |
          mvn -B -DskipTests pmd:pmd

      - name: Upload rosetta-source PDM reports artifact
        uses: actions/upload-artifact@v4
        with:
          name: rosetta-source/target/reports/
          path: rosetta-source-reports
          if-no-files-found: warn          
