name: CDM Build on Windows machine

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Debug cache
        run: |
          echo "Cache key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}"
          echo "POM files:"
          find . -name "pom.xml"
      - uses: actions/checkout@v3
      - uses: ./.github/actions/maven-build
